language: minimal

addons:
  apt:
    packages:
      - pandoc

git:
  depth: 150

deploy:
  on:
    tags: true

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh -g 1.13.2 | bash