local L = LibStub("AceLocale-3.0"):NewLocale("RUF", "enUS", true)
L["Open Configuration Panel"] = true
L["0%"] = true
L["100%"] = true
L["50%"] = true
L["Absorb"] = true
L["Absorb Bar Color, including opacity"] = true
L["Absorb Color"] = true
L["Absorb Texture"] = true
L["Additional Power Texture"] = true
L["Alpha"] = true
L["Always Hidden"] = true
L["Always Visible"] = true
L["Anchor"] = true
L["Anchor Frame"] = true
L["Anchor From"] = true
L["Anchor Point"] = true
L["Anchor Point on the unit frame."] = true
L["Anchor To"] = true
L["Animate"] = true
L["Animate bar changes."] = true
L["Appearance Options"] = true
L["Area on the anchor frame to anchor the unitframe to."] = true
L["arena"] = "Arena"
L["arena1"] = "Arena 1"
L["arena2"] = "Arena 2"
L["arena3"] = "Arena 3"
L["arena4"] = "Arena 4"
L["arena5"] = "Arena 5"
L["arenatarget"] = "Arena Targets"
L["arenaunits"] = "Arena Units"
L["Background"] = true
L["Background Alpha"] = true
L["Background Color"] = true
L["Background Color to use if not using the bar's color."] = true
L["Bar Order"] = true
L["Bars"] = true
L["Base Color"] = true
L["Base color. Other options take precedent."] = true
L["Base Text Color"] = true
L["Border"] = true
L["Border Size"] = true
L["Border Texture"] = true
L["boss"] = "Boss"
L["boss1"] = "Boss 1"
L["boss2"] = "Boss 2"
L["boss3"] = "Boss 3"
L["boss4"] = "Boss 4"
L["boss5"] = "Boss 5"
L["bosstarget"] = "Boss Targets"
L["bossunits"] = "Boss Units"
L["Bottom"] = true
L["Bottom-left"] = true
L["Bottom-right"] = true
L["Brightness Multiplier"] = true
L["Center"] = true
L["Choose if text is Capitalised, All Lower Case or all Upper case."] = true
L["Class"] = true
L["Class Colors"] = true
L["Class First, Power Second"] = true
L["Class Power Bar Texture"] = true
L["Class Power Height"] = true
L["Color at 0%"] = true
L["Color at 100%"] = true
L["Color at 100%."] = true
L["Color at 50%"] = true
L["Color Bar by percentage colors."] = true
L["Color by class"] = true
L["Color by percentage"] = true
L["Color by percentage at max"] = true
L["Color by power type"] = true
L["Color by reaction"] = true
L["Color Class"] = true
L["Color Disconnected"] = true
L["Color if unit is disconnected"] = true
L["Color if unit is tapped"] = true
L["Color Level"] = true
L["Color Percentage"] = true
L["Color Percentage At Max"] = true
L["Color player by class"] = true
L["Color player units by class color."] = true
L["Color Power Type"] = true
L["Color Reaction"] = true
L["Color Tapped"] = true
L["Color the background the same as the bar's color. Brightness reduced by the Multiplier setting."] = true
L["Color the frame border by the type of debuff you have."] = true
L["Color unit by reaction toward the player."] = true
L["Color used if none of the other options are checked."] = true
L["Colors"] = true
L["Colors the bar using the disconnected color if the unit is disconnected."] = true
L["Colors the bar using the power color."] = true
L["Colors the bar using the tapped color if the unit is tapped."] = true
L["Combat"] = true
L["Dead"] = true
L["Debuff Highlighting"] = true
L["Difficulty Colors"] = true
L["Disconnected"] = true
L["Disconnected Color"] = true
L["Display Style"] = true
L["Easy"] = true
L["Enable Health Text"] = true
L["Enable Level Text"] = true
L["Enable Name Text"] = true
L["Enable Power Text"] = true
L["Enable the Unit Frame."] = true
L["Enabled"] = true
L["Exalted"] = true
L["Fade out of Range"] = true
L["Fade the unit frame it the target is out of range of your spells."] = true
L["Fill Type"] = true
L["focus"] = "Focus"
L["focustarget"] = "Focus Target"
L["Font"] = true
L["Font Settings"] = true
L["Font Size"] = true
L["Frame Position Settings"] = true
L["Frame Settings"] = true
L["Frame Width"] = true
L["Friendly"] = true
L["Friendly Pet"] = true
L["Full"] = true
L["Ghost"] = true
L["Global Options"] = true
L["Half"] = true
L["Hard"] = true
L["Hated"] = true
L["Health"] = true
L["Health Bar Overlay"] = true
L["Health Bar Settings"] = true
L["Health Color"] = true
L["Health Height"] = true
L["Health Tag"] = true
L["Health Text"] = true
L["Health Texture"] = true
L["Height"] = true
L["Height of the Class Power bar."] = true
L["Height of the Health bar."] = true
L["Height of the Power bar."] = true
L["Hidden at 0"] = true
L["Honored"] = true
L["Horizontal Offset from the Anchor."] = true
L["Horizontal Offset from the Frame Anchor."] = true
L["Hostile"] = true
L["Indicators"] = true
L["If Class and Power bars are anchored to the same location, choose which bar is closest to the order."] = true
L["Left"] = true
L["Level"] = "Status: Level"
L["Level Tag"] = true
L["Level Text"] = true
L["Location area of the Unitframe to anchor from."] = true
L["Lower Case"] = true
L["Misc Colors"] = true
L["Monochrome"] = true
L["Monochrome Outline"] = true
L["Monochrome Thick Outline"] = true
L["Name"] = "Status: Name"
L["Name Tag"] = true
L["Name Text"] = true
L["Neutral"] = true
L["Nickname"] = true
L["Nickname Settings"] = true
L["None"] = true
L["Normal"] = true
L["Not Yet Implemented."] = true
L["Offline"] = true
L["Out of Range transparency"] = true
L["Outline"] = true
L["Overlay Alpha"] = true
L["Paragon"] = true
L["party"] = "Party"
L["party1"] = "Party 1"
L["party2"] = "Party 2"
L["party3"] = "Party 3"
L["party4"] = "Party 4"
L["partytarget"] = "Party Targets"
L["partyunits"] = "Party Units"
L["pet"] = "Pet"
L["pettarget"] = "Pet's Target"
L["player"] = "Player"
L["Point on the anchor frame to anchor to."] = true
L["Power"] = true
L["Power Bar Settings"] = true
L["Power Color"] = true
L["Power Colors"] = true
L["Power First, Class Second"] = true
L["Power Height"] = true
L["Power Tag"] = true
L["Power Text"] = true
L["Power Texture"] = true
L["Reaction Colors"] = true
L["Reduce background color's brightness by this percentage."] = true
L["Reduce Bar color's brightness by this percentage."] = true
L["Reduce each segment's brightness by this percentage."] = true
L["Relative Point"] = true
L["Revered"] = true
L["Reverse"] = true
L["Right"] = true
L["Runes - Blood"] = true
L["Runes - Frost"] = true
L["Runes - Unholy"] = true
L["Stagger - Low"] = true
L["Stagger - Medium"] = true
L["Stagger - High"] = true
L["Segment Multiplier"] = true
L["Separate Bar"] = true
L["Set the Absorb bar texture."] = true
L["Set the Additional Power bar texture."] = true
L["Set the Class power bar texture."] = true
L["Set the font used on all unit frames."] = true
L["Set the Health bar texture."] = true
L["Set the name of the frame for the unit to anchor to. Defaults to UI Parent if set blank."] = true
L["Set the Power bar texture."] = true
L["Settings for individual units."] = true
L["Settings for text elements."] = true
L["Show Additional Power"] = true
L["Show Power"] = true
L["Standard"] = true
L["Tag"] = true
L["Tags"] = true
L["Tapped"] = true
L["Tapped Color"] = true
L["target"] = "Target"
L["targettarget"] = "Target's Target"
L["Text Case"] = true
L["Text Options"] = true
L["Texts"] = true
L["Texture"] = true
L["The name of the frame for the unit to anchor to. Defaults to UI Parent if set blank."] = true
L["These settings affect all frames."] = true
L["Thick Outline"] = true
L["Top"] = true
L["Top-left"] = true
L["Top-right"] = true
L["Trivial"] = true
L["Type"] = true
L["Unfriendly"] = true
L["Unit Options"] = true
L["Upper Case"] = true
L["Use Bar Color"] = true
L["Use colors from the Class Colors addon"] = true
L["Vertical Offset from the Anchor."] = true
L["Vertical Offset from the Frame Anchor."] = true
L["Very Hard"] = true
L["Width"] = true
L["Width of the Unitframe."] = true
L["X Offset"] = true
L["Y Offset"] = true
L["Offset"] = true
L["You can set a nickname to replace your character's name on all RUF frames. Leave blank for your character's name."] = true
L["Zero"] = true
L["Test Mode"] = true
L["Shows all unitframes so you can easily configure them."] = true
L["Frame Lock"] = true
L["Allow unit frames to be repositioned by dragging."] = true
L["Up"] = true
L["Down"] = true
L["Growth Direction"] = true
L["Grow up or down."] = true
L["Y Spacing"] = true
L["Vertical Offset from the previous unit in the group."] = true
L["X Spacing"] = true
L["Horizontal Offset from the previous unit in the group."] = true


L["CurHPPerc"] = "Health: Cur - %"
L["CurHP"] = "Health: Cur"
L["HPPerc"] = "Health: %"
L["CurManaPerc"] = "Mana: Cur - % < 100"
L["CurMana"] = "Mana: Cur"
L["ManaPerc"] = "Mana: %"
L["CurPowerPerc"] = "Power: Cur - % < 100"
L["CurPower"] = "Power: Cur"
L["PowerPerc"] = "Power: %"
L["AFKDND"] = "Status: AFK or DND"

L["Hide the level text if the unit is the same level as you."] = true
L["Hide same level"] = true
L["Frame"] = true
L["Add Text Area"] = true
L["Add a Text Area for this unit with this name."] = true
L["Remove Text Area"] = true
L["Remove Text Area from this unit with this name."] = true
L["Hide this tag at 0 or always display."] = true
L["Set Blizard Default"] = true
L["Set class colors to the default Blizzard colors."] = true
L["Limit text width."] = true
L["Anchor Text"] = true
L["Max Width"] = true
L["Character Limit"] = true
L["Abbreviate Character Names longer than this. Set 0 for no limit."] = true
L["Attach To"] = true
L["Choose an element to attach to, either the frame or another text area."] = true
L["Show Unit in Test Mode."] = true
L["Displays the name of the unit frame in test mode."] = true
L["Hide if Primary Power is Mana."]  = true
L["Sets this to hidden if your primary resource is mana, so it only shows if you have a class resource, such as Maelstrom."]  = true
L['A text area with that name already exists!'] = true
L["Sort Direction"] = true
L["Shadow"] = true
L["Enable Text Shadow"] = true

L["Assist"] = true
L["Honor"] = true
L["Leader"] = true
L["Main Tank / Assist"] = true
L["Phased"] = true
L["PvP"] = true
L["Quest"] = true
L["Ready Check"] = true
L["Resting"] = true
L["Group Role"] = true
L["Target Markers"] = true
L["Size"] = true
L["Area on the anchor frame to anchor the indicator to."] = true
L["Choose an element to attach to, either the frame or another indicator."] = true
L["Location area of the Indicator to anchor from."] = true
L["Enable Badge"] = true
L["Always Show"] = true



L["Feedback"] = true
L["Current Revision"] = true
L["When reporting an issue, please also post the revision number above. Thanks!"] = true
L["Invite Link"] = true


L["Rows"] = true
L["Columns"] = true
L["Horizontal Spacing"] = true
L["Vertical Spacing"] = true
L["Horizontal Growth"] = true
L["Ascending"] = true
L["Descending"] = true
L["Vertical Growth"] = true
L["Direction"] = true
L["Sort By"] = true
L["Alphabetically"] = true
L["Duration"] = true
L["Index"] = true
L["Player"] = true
L["Time Remaining"] = true
L["Debuff Icons"] = true
L["Click Through"] = true


L["Auras"] = true
L["Aura Highlighting"] = true
L["Default Buff Glow"] = true
L["Default Debuff Glow"] = true
L["Magic"] = true
L["Disease"] = true
L["Curse"] = true
L["Poison"] = true
L["Enrage"] = true
L["Color Buffs by Type"] = true
L["Color Debuffs by Type"] = true
L["Color only removable"] = true
L["Highlight Texture"] = true
L["Highlight Size"] = true
L["Border Color"] = true
L["Filtering"] = true
L["Buffs"] = true
L["Sorting"] = true
L["Anchoring"] = true
L["Show Player"] = true
L["Show Buffs cast by "] = true
L[" on this unit."] = true
L["Show "] = true
L["Show Group Members"] = true
L["group members"] = true
L["Show Others"] = true
L["others"] = true
L["Minimum Duration"] = true
L["Maximum Duration"] = true
L["Show Unlimited Duration"] = true
L["Max Auras"] = true
L["Debuffs"] = true
L["Buff Icons"] = true
L["Show Debuffs cast by "] = true
L["Show Only Dispellable"] = true
L["Show only auras you can dispel"] = true
L["Style"] = true
L["Changes Indicator icon style. Requires a UI Reload to take effect."] = true
L["Blizzard Icons"] = true
L["RUF Icons"] = true
L["Cannot configure while in combat."] = true
L['Power First, Class Second, Absorb Third'] = true
L['Power First, Absorb Second, Class Third'] = true
L['Class First, Power Second, Absorb Third'] = true
L['Class First, Absorb Second, Power Third'] = true
L['Absorb First, Power Second, Class Third'] = true
L['Absorb First, Class Second, Power Third'] = true
L['InCombat'] = 'In Combat'
L['Lead'] = 'Leader'
L['MainTankAssist'] = 'Main Tank & Assist'
L['PvPCombat'] = 'PvP'
L['Objective'] = 'Quest Objective'
L['Ready'] = 'Ready Check Status'
L['Rest'] = 'Resting'
L['Role'] = 'Group Role'
L['TargetMark'] = 'Target Marks'
L['Global Appearance Options'] = true
L['LootMaster'] = 'Master Looter'
L['Curseforge'] = true
L['Discord'] = true
L['URL'] = true
L['MaxHP'] = 'Health: Max'
L['CurMaxHPPerc'] = 'Health: Cur/Max - %'
L['Show Percentage at Max'] = true
L['Show Max at Max'] = true