local L = LibStub("AceLocale-3.0"):NewLocale("RUF", "enUS", true)
L["0%"] = true
L["100%"] = true
L["50%"] = true
L["A text area with that name already exists!"] = true
L["Abbreviate Character Names longer than this. Set 0 for no limit."] = true
L["Absorb"] = true
L["Accept"] = true
L["Add a Text Area for this unit with this name."] = true
L["Add Text Area"] = true
L["AFKDND"] = "Status: AFK or DND"
L["Allow unit frames to be repositioned by dragging."] = true
L["Alpha"] = true
L["Alphabetically"] = true
L["Always Hidden"] = true
L["Always Visible"] = true
L["Anchor"] = true
L["Anchor Frame"] = true
L["Anchor From"] = true
L["Anchor Point"] = true
L["Anchor Text"] = true
L["Anchor To"] = true
L["Anchoring"] = true
L["Animate"] = true
L["Appearance Options"] = true
L["Area on the anchor frame to anchor the indicator to."] = true
L["Area on the anchor frame to anchor the unitframe to."] = true
L["arena"] = "Arena"
L["arena1"] = "Arena 1"
L["arena2"] = "Arena 2"
L["arena3"] = "Arena 3"
L["arena4"] = "Arena 4"
L["arena5"] = "Arena 5"
L["arenatarget"] = "Arena Targets"
L["arenaunits"] = "Arena Units"
L["Ascending"] = true
L["Assist"] = true
L["Attach To"] = true
L["Auras"] = true
L["Background Alpha"] = true
L["Background Color"] = true
L["Background Color to use if not using the bar's color."] = true
L["Bars"] = true
L["Base Color"] = true
L["Border"] = true
L["boss"] = "Boss"
L["boss1"] = "Boss 1"
L["boss2"] = "Boss 2"
L["boss3"] = "Boss 3"
L["boss4"] = "Boss 4"
L["boss5"] = "Boss 5"
L["bosstarget"] = "Boss Targets"
L["Bottom"] = true
L["Bottom-left"] = true
L["Bottom-right"] = true
L["Brightness Multiplier"] = true
L["Buff Icons"] = true
L["Buffs"] = true
L["Cannot configure while in combat."] = true
L["Center"] = true
L["Character Limit"] = true
L["Choose an element to attach to, either the frame or another indicator."] = true
L["Choose an element to attach to, either the frame or another text area."] = true
L["Choose if text is Capitalised, All Lower Case or all Upper case."] = true
L["Class"] = true
L["Class Colors"] = true
L["Click Through"] = true
L["Color at 0%"] = true
L["Color at 100%"] = true
L["Color at 50%"] = true
L["Color Bar by percentage colors."] = true
L["Color Buffs by Type"] = true
L["Color Class"] = true
L["Color Debuffs by Type"] = true
L["Color Disconnected"] = true
L["Color Level"] = true
L["Color only removable"] = true
L["Color Percentage"] = true
L["Color Percentage At Max"] = true
L["Color player units by class color."] = true
L["Color Power Type"] = true
L["Color Reaction"] = true
L["Color Tapped"] = true
L["Color the background the same as the bar's color. Brightness reduced by the Multiplier setting."] = true
L["Color unit by reaction toward the player."] = true
L["Color used if none of the other options are checked."] = true
L["Colors"] = true
L["Colors the bar using the disconnected color if the unit is disconnected."] = true
L["Colors the bar using the power color."] = true
L["Colors the bar using the tapped color if the unit is tapped."] = true
L["Columns"] = true
L["Combat"] = true
L["CurHP"] = "Health: Cur"
L["CurHPPerc"] = "Health: Cur - %"
L["CurMana"] = "Mana: Cur"
L["CurManaPerc"] = "Mana: Cur - % < 100"
L["CurMaxHPPerc"] = "Health: Cur/Max - %"
L["CurPower"] = "Power: Cur"
L["CurPowerPerc"] = "Power: Cur - % < 100"
L["Current Version: %s"] = true
L["Curse"] = true
L["Curseforge"] = true
L["Dead"] = true
L["Debuff Icons"] = true
L["Debuffs"] = true
L["Default Buff Glow"] = true
L["Default Debuff Glow"] = true
L["Descending"] = true
L["Difficulty Colors"] = true
L["Direction"] = true
L["Disconnected"] = true
L["Discord"] = true
L["Disease"] = true
L["Display Style"] = true
L["Displays the name of the unit frame in test mode."] = true
L["Down"] = true
L["Duration"] = true
L["Easy"] = true
L["Enable Text Shadow"] = true
L["Enable the Unit Frame."] = true
L["Enabled"] = true
L["Enrage"] = true
L["Fade out of Range"] = true
L["Fade the unit frame it the target is out of range of your spells."] = true
L["Feedback"] = true
L["Fill Type"] = true
L["Filtering"] = true
L["focus"] = "Focus"
L["focustarget"] = "Focus Target"
L["Font"] = true
L["Font Size"] = true
L["Frame"] = true
L["Frame Lock"] = true
L["Friendly"] = true
L["Friendly Pet"] = true
L["Ghost"] = true
L["Global Appearance Options"] = true
L["group members"] = true
L["Grow up or down."] = true
L["Growth Direction"] = true
L["Hard"] = true
L["Health"] = true
L["Health Bar Overlay"] = true
L["Height"] = true
L["Hidden at 0"] = true
L["Hide if Primary Power is Mana."] = true
L["Hide same level"] = true
L["Hide the level text if the unit is the same level as you."] = true
L["Hide this tag at 0 or always display."] = true
L["Highlight Texture"] = true
L["Honor"] = true
L["Horizontal Growth"] = true
L["Horizontal Offset from the Anchor."] = true
L["Horizontal Offset from the Frame Anchor."] = true
L["Horizontal Offset from the previous unit in the group."] = true
L["Horizontal Spacing"] = true
L["HPPerc"] = "Health: %"
L["InCombat"] = "In Combat"
L["Index"] = true
L["Indicators"] = true
L["Invite Link"] = true
L["Lead"] = "Leader"
L["Left"] = true
L["Level"] = "Status: Level"
L["Level Text"] = true
L["Location area of the Indicator to anchor from."] = true
L["Location area of the Unitframe to anchor from."] = true
L["LootMaster"] = "Master Looter"
L["Lower Case"] = true
L["Magic"] = true
L["MainTankAssist"] = "Main Tank & Assist"
L["ManaPerc"] = "Mana: %"
L["Max Auras"] = true
L["MaxHP"] = "Health: Max"
L["Maximum Duration"] = true
L["Minimum Duration"] = true
L["Misc Colors"] = true
L["Monochrome"] = true
L["Monochrome Outline"] = true
L["Monochrome Thick Outline"] = true
L["Name"] = "Status: Name"
L["Nickname"] = true
L["None"] = true
L["Normal"] = true
L["Objective"] = "Quest Objective"
L["Offline"] = true
L["Offset"] = true
L["Open Configuration Panel"] = true
L["others"] = true
L["Out of Range transparency"] = true
L["Outline"] = true
L["Overlay Alpha"] = true
L["Paragon"] = true
L["party"] = "Party"
L["party1"] = "Party 1"
L["party2"] = "Party 2"
L["party3"] = "Party 3"
L["party4"] = "Party 4"
L["party5"] = "Party 5"
L["pet"] = "Pet"
L["PetHappiness"] = "Pet Happiness"
L["pettarget"] = "Pet's Target"
L["Phased"] = true
L["Player"] = true
L["player"] = "Player"
L["Poison"] = true
L["Power"] = true
L["Power Color"] = true
L["Power Colors"] = true
L["Power Height"] = true
L["Power Tag"] = true
L["Power Text"] = true
L["Power Texture"] = true
L["PowerPerc"] = "Power: %"
L["PvPCombat"] = "PvP"
L["Reaction Colors"] = true
L["Ready"] = "Ready Check Status"
L["Reduce background color's brightness by this percentage."] = true
L["Reduce Bar color's brightness by this percentage."] = true
L["Reduce each segment's brightness by this percentage."] = true
L["Remove Text Area"] = true
L["Remove Text Area from this unit with this name."] = true
L["Rest"] = "Resting"
L["Reverse"] = true
L["Right"] = true
L["Role"] = "Group Role"
L["Rows"] = true
L["RUF [|c5500DBBDRaeli's Unit Frames|r] needs to reload your UI to properly finish installing on first use. Please do this now."] = true
L["Runes - Blood"] = true
L["Runes - Frost"] = true
L["Runes - Unholy"] = true
L["Segment Multiplier"] = true
L["Separate Bar"] = true
L["Sets this to hidden if your primary resource is mana, so it only shows if you have a class resource, such as Maelstrom."] = true
L["Shadow"] = true
L["Show %s"] = true
L["Show buffs cast by %s on this unit."] = true
L["Show Classification"] = true
L["Show debuffs cast by %s on this unit."] = true
L["Show Group Members"] = true
L["Show Level"] = true
L["Show Max at Max"] = true
L["Show only auras you can dispel"] = true
L["Show Only Dispellable"] = true
L["Show Others"] = true
L["Show Percentage at Max"] = true
L["Show Player"] = true
L["Show the ++ for rare elites, + for elites etc."] = true
L["Show Unit in Test Mode."] = true
L["Show Unlimited Duration"] = true
L["Shows all unitframes so you can easily configure them."] = true
L["Size"] = true
L["Sort By"] = true
L["Sort Direction"] = true
L["Sorting"] = true
L["Stagger - High"] = true
L["Stagger - Low"] = true
L["Stagger - Medium"] = true
L["Standard"] = true
L["Tag"] = true
L["Tags"] = true
L["Tapped"] = true
L["target"] = "Target"
L["TargetMark"] = "Target Marks"
L["targettarget"] = "Target's Target"
L["Test Mode"] = true
L["Text Case"] = true
L["Texts"] = true
L["Texture"] = true
L["The name of the frame for the unit to anchor to. Defaults to UI Parent if set blank."] = true
L["These settings affect all frames."] = true
L["Thick Outline"] = true
L["This syncs with other addons that support NickTag-1.0 such as Details!"] = true
L["Time Remaining"] = true
L["Top"] = true
L["Top-left"] = true
L["Top-right"] = true
L["Trivial"] = true
L["Type"] = true
L["Unfriendly"] = true
L["Unit Options"] = true
L["Up"] = true
L["Upper Case"] = true
L["URL"] = true
L["Use Bar Color"] = true
L["Vertical Growth"] = true
L["Vertical Offset from the Anchor."] = true
L["Vertical Offset from the Frame Anchor."] = true
L["Vertical Offset from the previous unit in the group."] = true
L["Vertical Spacing"] = true
L["Very Hard"] = true
L["When reporting an issue, please also post the revision number above. Thanks!"] = true
L["Width"] = true
L["X Offset"] = true
L["X Spacing"] = true
L["Y Offset"] = true
L["Y Spacing"] = true
L["Latency"] = true
L["Color"] = true
L["Cast Bar"] = true
L["Anchor to Unit Frame"] = true
L["Attach to the unit frame or allow free placement."] = true
L["Highlight Thickness"] = true
L["Thickness of the highlight."] = true
L["Size relative to the aura icon"] = true
L["Icon Height"] = true
L["Icon Width"] = true
L["Frame Highlighting"] = true
L["Color auras by type only if you can dispel / purge them."] = true
L["Thickness of the highlight."] = true
L["Aura Highlight Glow"] = true
L["Simple Border"] = true
L["Inset from icon edge"] = true
L["Inset from frame edge"] = true
L["Aura Colors"] = true
L["Frame Border"] = true
L["Use Class Colors addon"] = true
L["Sets if RUF will use class colours from the Class Colors addon if you have it installed."] = true
L["Use Blizard Colors"] = true
L["Set class colors to the default Blizzard colors."] = true
L["Foreground Style"] = true
L["Background Style"] = true
L["Color 0% by Power Type"] = true
L["Colour bar by power color when at 0%."] = true
L["Color 0% by Class"] = true
L["Colour bar by class color when at 0%."] = true
L["Color 50% by Power Type"] = true
L["Colour bar by power color when at 50%."] = true
L["Color 50% by Class"] = true
L["Colour bar by class color when at 50%."] = true
L["Color 100% by Power Type"] = true
L["Colour bar by power color when at 100%."] = true
L["Color 100% by Class"] = true
L["Colour bar by class color when at 100%."] = true
L["The colour options below are listed in order of precedence left to right, with the first being the highest priority."] = true
L["Other Global Settings"] = true
L["Combat Fading"] = true
L["Targeting alpha"] = true
L["Alpha of all frames when you are targeting something."] = true
L["In combat alpha"] = true
L["Out of combat alpha"] = true
L["Enable targeting alpha"] = true
L["Use a different alpha value when you have a target."] = true
L["The border on buff or debuff icons that is colored using the colors above."] = true
L["A simple border around the edge of each buff or debuff icon."] = true
L["The unit frame border that glows when the unit has a dispellable buff or debuff."] = true
L["Play sound on highlight"] = true
L["Plays a sound when a removable aura is found on a unit. Does not affect target units."] = true
L["Sound"] = true
L["Justify"] = true
L["Custom Width"] = true
L["Toggle on to force text element to be set to a custom width. If the text is longer than the width, truncation will occur."] = true
L["Color Not Interruptible"] = true
L["Enable to force the bar to a specific color if the cast cannot be interrupted."] = true
L["Not Interruptible Color"] = true
L["Copy Settings from:"] = true
L["Copy and replace all text elements from the selected unit to this unit."] = true
L["Are you sure you want to replace these settings? You cannot undo this change."] = true
L["partypet"] = "Party Pets"
L["partypet1"] = "Party Pet 1"
L["partypet2"] = "Party Pet 2"
L["partypet3"] = "Party Pet 3"
L["partypet4"] = "Party Pet 4"
L["partypet5"] = "Party Pet 5"
L["Show in Raid"] = true
L["Portrait"] = true
L["Unitframe Overlay"] = true
L["Free floating"] = true
L["Background"] = true
L["Model Appearance"] = true
L["Freeze Animation"] = true
L["Rotation"] = true
L["Camera Distance"] = true
L["Z Offset"] = true
L["Portrait Zoom"] = true
L["Position"] = true
L["Smoothly animate bar changes. Does not affect class resources that are split into chunks such as Combo Points, or Holy Power."] = true
L["Health Cutaway"] = true
L["Makes the portrait disappear with the health bar as it lowers."] = true
L["Heal Prediction"] = true
L["Player Heals"] = true
L["Other's Heals"] = true
L["Bar Overflow Amount"] = true
L["Allows incoming healing bars to overflow out of the frame by this amount. The value is a percentage of the frame's width. Set to 0 to disallow overflowing."] = true
L["You have the %s version of RUF installed, but you are playing %s. Please install a compatible version."] = true
L["Retail"] = true
L["Classic"] = true
L["Desaturate"] = true
L["Copy and replace settings from the selected unit to this unit."] = true
L["Show Classification before Level"] = true
L["%s, %s, and class specific resources for other classes."] = true
L["%s and class specific resources for other classes."] = true
L["Abbreviate Style"] = true
L["Trim simply removes any letters above the limit.\nElipsis adds an elipsis to the end of the trimmed name to signify it has been cut short.\nAbbreviate turns any words that would be trimmed into an initial.\nInitialism turns the entire name into initials if it would be trimmed."] = true
L["Trim"] = true
L["Elipsis"] = true
L["Abbreviate"] = true
L["Initialism"] = true