local L = LibStub("AceLocale-3.0"):NewLocale("RUF", "koKR")
L = L or {}
--[[Translation missing --]]
L["%s and class specific resources for other classes."] = "%s and class specific resources for other classes."
--[[Translation missing --]]
L["%s, %s, and class specific resources for other classes."] = "%s, %s, and class specific resources for other classes."
L["0%"] = true
L["100%"] = true
L["50%"] = true
L["A simple border around the edge of each buff or debuff icon."] = "각 버프나 디버프 아이콘의 가장자리를 감싸는 간단한 테두리입니다."
--[[Translation missing --]]
L["A text area with that name already exists!"] = "A text area with that name already exists!"
--[[Translation missing --]]
L["Abbreviate"] = "Abbreviate"
--[[Translation missing --]]
L["Abbreviate Character Names longer than this. Set 0 for no limit."] = "Abbreviate Character Names longer than this. Set 0 for no limit."
--[[Translation missing --]]
L["Abbreviate Style"] = "Abbreviate Style"
L["Absorb"] = "흡수"
L["Accept"] = "수락"
L["Add a Text Area for this unit with this name."] = "이 이름을 이 유닛의 문자 영역으로 추가합니다."
L["Add Text Area"] = "문자 영역 추가"
L["AFKDND"] = "상태: 자리비움 또는 다른용무중"
L["Allow unit frames to be repositioned by dragging."] = "드래그하여 유닛 프레임 재배치를 허용합니다."
L["Allows incoming healing bars to overflow out of the frame by this amount. The value is a percentage of the frame's width. Set to 0 to disallow overflowing."] = "들어오는 치유 바는 이 양에 비해 프레임 밖으로 넘어가는 것을 허용합니다. 값은 프레임 너비의 백분율입니다. 넘치는 것을 허용하지 않으면 0으로 설정하세요."
L["Alpha"] = "투명도"
L["Alpha of all frames when you are targeting something."] = "무언가를 대상으로 선택 할 때 모든 프레임의 투명도입니다."
--[[Translation missing --]]
L["Alpha of the player frame when you are under max health."] = "Alpha of the player frame when you are under max health."
--[[Translation missing --]]
L["Alphabetically"] = "Alphabetically"
L["Always Hidden"] = "항상 숨김"
L["Always Visible"] = "항상 보임"
L["Anchor"] = "기준"
L["Anchor Frame"] = "기준 프레임"
--[[Translation missing --]]
L["Anchor From"] = "Anchor From"
--[[Translation missing --]]
L["Anchor Point"] = "Anchor Point"
--[[Translation missing --]]
L["Anchor Text"] = "Anchor Text"
L["Anchor To"] = "기준"
L["Anchor to Unit Frame"] = "유닛 프레임 기준"
--[[Translation missing --]]
L["Anchoring"] = "Anchoring"
L["Animate"] = "애니메이션"
L["Appearance Options"] = "외관 옵션"
L["Are you sure you want to replace these settings? You cannot undo this change."] = "이 설정을 바꾸시겠습니까? 이 변경은 취소할 수 없습니다."
--[[Translation missing --]]
L["Area on the anchor frame to anchor the indicator to."] = "Area on the anchor frame to anchor the indicator to."
--[[Translation missing --]]
L["Area on the anchor frame to anchor the unitframe to."] = "Area on the anchor frame to anchor the unitframe to."
L["arena"] = "투기장"
--[[Translation missing --]]
L["arena %s"] = "Arena %s"
L["arenatarget"] = "투기장 대상"
--[[Translation missing --]]
L["arenatarget %s"] = "Arena Target %s"
L["arenaunits"] = "투기장 유닛"
L["Ascending"] = "오름차순"
L["Assist"] = "지원"
L["Attach To"] = "부착"
L["Attach to the unit frame or allow free placement."] = "유닛 프렝임에 부착하거나 자유 배치를 허용합니다."
--[[Translation missing --]]
L["Attached"] = "Attached"
L["Aura Colors"] = "오라 색상"
L["Aura Highlight Glow"] = "오라 강조 반짝임"
L["Auras"] = "오라"
L["Background"] = "배경"
L["Background Alpha"] = "배경 투명도"
L["Background Color"] = "배경 색상"
L["Background Color to use if not using the bar's color."] = "바의 색상을 사용하지 않으면 배경 색상을 사용합니다."
L["Background Style"] = "배경 스타일"
L["Bar Overflow Amount"] = "바 넘침 양"
L["Bars"] = "바"
L["Base Color"] = "기본 색상"
L["Border"] = "테두리"
L["boss"] = "보스"
--[[Translation missing --]]
L["boss %s"] = "Boss %s"
L["bosstarget"] = "보스 표적"
--[[Translation missing --]]
L["bosstarget %s"] = "Boss Target %s"
L["Bottom"] = "하단"
L["Bottom-left"] = "왼쪽 하단"
L["Bottom-right"] = "오른쪽 하단"
L["Brightness Multiplier"] = "밝기 배율"
L["Buff Icons"] = "버프 아이콘"
L["Buffs"] = "버프"
L["Camera Distance"] = "카메라 거리"
L["Cannot configure while in combat."] = "전투 중에는 구성 할 수 없습니다."
L["Cast Bar"] = "시전 바"
L["Center"] = "중앙"
--[[Translation missing --]]
L["Character Limit"] = "Character Limit"
L["Choose an element to attach to, either the frame or another indicator."] = "프레임 또는 다른 지시기에 첨부할 요소를 선택하세요."
L["Choose an element to attach to, either the frame or another text area."] = "프레임 또는 다른 문자 영역에 첨부할 요소를 선택하세요."
L["Choose if text is Capitalised, All Lower Case or all Upper case."] = "문자가 대문자, 모두 소문자 또는 모두 대문자면 선택하세요."
L["Class"] = "직업"
L["Class Colors"] = "직업 색상"
L["Classic"] = "클래식"
L["Click Through"] = "클릭을 통해"
L["Color"] = "색상"
L["Color 0% by Class"] = "직업 별 색상 0%"
L["Color 0% by Power Type"] = "자원 유형 별 색상 0%"
L["Color 100% by Class"] = "직업 별 색상 100%"
L["Color 100% by Power Type"] = "자원 유형 별 색상 100%"
L["Color 50% by Class"] = "직업 별 색상 50%"
L["Color 50% by Power Type"] = "자원 유형 별 색상 50%"
L["Color at 0%"] = "0% 색상"
L["Color at 100%"] = "100% 색상"
L["Color at 50%"] = "50% 색상"
L["Color auras by type only if you can dispel / purge them."] = "해제/제거 가능한 유형의 오라만 색상을 입힙니다."
L["Color Bar by percentage colors."] = "백분율 색상 별 색상 바"
L["Color Buffs by Type"] = "유형 별 버프 색상"
L["Color Class"] = "직업 색상"
L["Color Debuffs by Type"] = "유형 별 디버프 색상"
L["Color Disconnected"] = "접속종료 색상"
L["Color Level"] = "레벨 색상"
L["Color Not Interruptible"] = "차단 불가 색상"
L["Color only removable"] = "색상만 제거가능"
L["Color Percentage"] = "색상 비율"
L["Color Percentage At Max"] = "최대 색상 비율"
L["Color player units by class color."] = "직업 색상 별 플레이어 유닛 색상"
L["Color Power Type"] = "자원 유형 색상"
L["Color Reaction"] = "반응 색상"
L["Color Tapped"] = "클릭 시 색상"
L["Color the background the same as the bar's color. Brightness reduced by the Multiplier setting."] = "바의 색상과 같은 배경 색입니다. 배율 설정으로 밝기가 감소됩니다."
L["Color unit by reaction toward the player."] = "플레이어에 대한 반응 별 유닛 색상"
L["Color used if none of the other options are checked."] = "다른 옵션을 확인하지 않은 경우 사용되는 색상"
L["Colors"] = "색상"
L["Colors the bar using the disconnected color if the unit is disconnected."] = "유닛이 접속종료되면 접속종료 색상을 색상 바로 사용합니다."
L["Colors the bar using the power color."] = "자원 색상을 색상 바로 사용합니다."
L["Colors the bar using the tapped color if the unit is tapped."] = "유닛이 클릭되면 클릭된 색상을 색상 바로 사용합니다."
L["Colour bar by class color when at 0%."] = "0% 일 때 직업 색상 별 색상 바."
L["Colour bar by class color when at 100%."] = "100% 일 때 직업 색상 별 색상 바."
L["Colour bar by class color when at 50%."] = "50% 일 때 직업 색상 별 색상 바."
L["Colour bar by power color when at 0%."] = "0% 일 때 자원 색상 별 색상 바."
L["Colour bar by power color when at 100%."] = "100% 일 때 자원 색상 별 색상 바."
L["Colour bar by power color when at 50%."] = "50% 일 때 자원 색상 별 색상 바."
L["Columns"] = "열"
L["Combat"] = "전투"
L["Combat Fading"] = "전투 사라짐"
--[[Translation missing --]]
L["Cooldown Sprial"] = "Cooldown Sprial"
L["Copy and replace all text elements from the selected unit to this unit."] = "이 유닛을 선택된 유닛으로부터 모든 문자 요소의 설정을 복사하고 교체합니다."
L["Copy and replace settings from the selected unit to this unit."] = "이 유닛을 선택된 유닛으로부터 설정을 복사하고 교체합니다."
L["Copy Settings from:"] = "다음에서 설정 복사:"
L["CurHP"] = "생명력: 현재"
L["CurHPPerc"] = "생명력: 현재 - %"
L["CurMana"] = "마나: 현재"
L["CurManaPerc"] = "마나: 현재 - % < 100"
--[[Translation missing --]]
L["CurMaxHP"] = "Health: Cur/Max"
L["CurMaxHPPerc"] = "생명력: 현재/최대 - %"
L["CurPower"] = "자원: 현재"
L["CurPowerPerc"] = "자원: 현재 - % < 100"
L["Current Version: %s"] = "현재 버전: %s"
L["Curse"] = "저주"
L["Curseforge"] = true
L["Custom Width"] = "사용자정의 너비"
--[[Translation missing --]]
L["Damaged alpha"] = "Damaged alpha"
L["Dead"] = "죽음"
L["Debuff Icons"] = "디버프 아이콘"
L["Debuffs"] = "디버프"
L["Default Buff Glow"] = "기본 버프 반짝임"
L["Default Debuff Glow"] = "기본 디버프 반짝임"
--[[Translation missing --]]
L["Desaturate"] = "Desaturate"
L["Descending"] = "내림차순"
L["Difficulty Colors"] = "난이도 색상"
L["Direction"] = "방향"
L["Disconnected"] = "접속종료"
--[[Translation missing --]]
L["Discord"] = "Discord"
L["Disease"] = "질병"
L["Display Style"] = "표시 스타일"
L["Displays the name of the unit frame in test mode."] = "테스트 모드에서 유닛 프레임의 이름을 표시합니다."
L["Down"] = "아래"
L["Duration"] = "지속시간"
--[[Translation missing --]]
L["Easy"] = "Easy"
--[[Translation missing --]]
L["Elipsis"] = "Elipsis"
--[[Translation missing --]]
L["Enable Nicknames"] = "Enable Nicknames"
--[[Translation missing --]]
L["Enable player damaged alpha"] = "Enable player damaged alpha"
L["Enable targeting alpha"] = "대상 선택 투명도 사용"
L["Enable Text Shadow"] = "문자 그림자 사용"
L["Enable the Unit Frame."] = "유닛 프레임 사용"
L["Enable to force the bar to a specific color if the cast cannot be interrupted."] = "시전을 중단 할 수 없는 경우 바를 특정 색상으로 강제 설정할 수 있습니다."
--[[Translation missing --]]
L["Enable to replace this unit frame with the vehicle frame when in a vehicle. If disabled, the pet frame will become the vehicle frame instead."] = "Enable to replace this unit frame with the vehicle frame when in a vehicle. If disabled, the pet frame will become the vehicle frame instead."
--[[Translation missing --]]
L["Enable to smoothly transition between different alpha values."] = "Enable to smoothly transition between different alpha values."
L["Enabled"] = "사용함"
--[[Translation missing --]]
L["Enables the cooldown spiral showing duration remaining on buff or debuff icons."] = "Enables the cooldown spiral showing duration remaining on buff or debuff icons."
L["Enrage"] = "분노"
L["Fade out of Range"] = "범위에서 사라짐"
L["Fade the unit frame it the target is out of range of your spells."] = "대상이 주문 범위를 벗어나면 유닛 프레임을 사라지게 합니다."
L["Feedback"] = "피드백"
L["Fill Type"] = "적용 유형"
--[[Translation missing --]]
L["Filtering"] = "Filtering"
L["focus"] = "집중"
L["focustarget"] = "주시 대상"
L["Font"] = "글꼴"
L["Font Size"] = "글꼴 크기"
L["Foreground Style"] = "전경 스타일"
L["Frame Border"] = "프레임 테두리"
L["Frame Highlighting"] = "프레임 강조"
L["Frame Lock"] = "프레임 고정"
--[[Translation missing --]]
L["Free floating"] = "Free floating"
L["Freeze Animation"] = "얼리는 애니메이션"
L["Friendly"] = "아군"
L["Friendly Pet"] = "아군의 소환수"
--[[Translation missing --]]
L["General"] = "General"
L["Ghost"] = "유령"
L["group members"] = "그룹원"
L["Grow up or down."] = "위나 아래로 성장"
L["Growth Direction"] = "성장 방향"
L["Hard"] = "어려움"
L["Heal Prediction"] = "치유 예측"
L["Health"] = "생명력"
L["Health Bar Overlay"] = "생명력 바 오버레이"
--[[Translation missing --]]
L["Health Cutaway"] = "Health Cutaway"
L["Height"] = "높이"
L["Hidden at 0"] = "0에 숨김"
L["Hide if Primary Power is Mana."] = "주력 자원이 마나이면 숨깁니다."
L["Hide same level"] = "동일 레벨 숨김"
L["Hide the level text if the unit is the same level as you."] = "유닛이 당신과 같은 레벨이면 레벨 문자를 숨깁니다."
L["Hide this tag at 0 or always display."] = "이 태그가 0이면 숨기거나 항상 표시합니다."
L["Highlight Texture"] = "강조 무늬"
L["Highlight Thickness"] = "강조 두께"
L["Honor"] = "명예"
--[[Translation missing --]]
L["Horizonal"] = "Horizonal"
L["Horizontal Growth"] = "수평 성장"
L["Horizontal Offset from the Anchor."] = "기준으로부터의 수평 좌표"
L["Horizontal Offset from the Frame Anchor."] = "프레임 기준으로부터의 수평 좌표입니다."
L["Horizontal Offset from the previous unit in the group."] = "그룹 안 이전 유닛으로부터의 수평 좌표입니다."
L["Horizontal Spacing"] = "수평 간격"
--[[Translation missing --]]
L["How long the frames take to smoothly transition between different alpha values."] = "How long the frames take to smoothly transition between different alpha values."
--[[Translation missing --]]
L["HPPerc"] = "Health: %"
L["Icon Height"] = "아이콘 높이"
L["Icon Width"] = "아이콘 너비"
L["In combat alpha"] = "전투 시 투명도"
L["InCombat"] = "전투 시"
L["Index"] = "항목"
L["Indicators"] = "표시기"
--[[Translation missing --]]
L["Initialism"] = "Initialism"
--[[Translation missing --]]
L["Inset from bar edge"] = "Inset from bar edge"
L["Inset from frame edge"] = "프레임 가장자리에 삽입"
L["Inset from icon edge"] = "아이콘 가장자리에 삽입"
L["Invite Link"] = "초대 링크"
L["Justify"] = "맞춤"
L["Latency"] = "지연"
--[[Translation missing --]]
L["Layout"] = "Layout"
L["Lead"] = "장"
L["Left"] = "왼쪽"
L["Level"] = "상태: 레벨"
L["Level Text"] = "레벨 문자"
--[[Translation missing --]]
L["Location area of the Indicator to anchor from."] = "Location area of the Indicator to anchor from."
--[[Translation missing --]]
L["Location area of the Unitframe to anchor from."] = "Location area of the Unitframe to anchor from."
L["LootMaster"] = "전리품 담당자"
L["Lower Case"] = "소문자"
L["Magic"] = "마법"
L["MainTankAssist"] = "방어 전담과 지원공격 전담"
--[[Translation missing --]]
L["Makes the portrait disappear with the health bar as it lowers."] = "Makes the portrait disappear with the health bar as it lowers."
L["ManaPerc"] = "마나: %"
--[[Translation missing --]]
L["Max"] = "Max"
L["Max Auras"] = "최대 오라"
L["MaxHP"] = "생명력: 최대"
L["Maximum Duration"] = "최대 지속시간"
L["Minimum Duration"] = "최소 지속시간"
L["Misc Colors"] = "기타 색상"
L["Model Appearance"] = "모델 외형"
L["Monochrome"] = "단색화"
L["Monochrome Outline"] = "단색 외곽선"
L["Monochrome Thick Outline"] = "단색 두꺼운 외곽선"
L["Name"] = "상태: 이름"
L["Nickname"] = "닉네임"
L["None"] = "없음"
L["Normal"] = "표준"
L["Not Interruptible Color"] = "차단 불가 색상"
L["Objective"] = "퀘스트 수행목표"
L["Offline"] = "접속종료"
L["Offset"] = "좌표"
L["Open Configuration Panel"] = "구성 패널 열기"
L["Other Global Settings"] = "그밖의 전역 설정"
--[[Translation missing --]]
L["others"] = "others"
L["Other's Heals"] = "그밖의 치유"
L["Out of combat alpha"] = "전투 벗어남 투명도"
L["Out of Range transparency"] = "범위 벗어남 투명도"
L["Outline"] = "외곽선"
L["Overlay Alpha"] = "오버레이 투명도"
--[[Translation missing --]]
L["Paragon"] = "Paragon"
L["party"] = "파티"
--[[Translation missing --]]
L["party %s"] = "Party %s"
L["partypet"] = "파티의 소환수"
--[[Translation missing --]]
L["partypet %s"] = "Party Pet %s"
--[[Translation missing --]]
L["partytarget"] = "Party Targets"
--[[Translation missing --]]
L["partytarget %s"] = "Party Target %s"
L["pet"] = "소환수"
L["PetHappiness"] = "소환수 만족도"
L["pettarget"] = "소환수의 대상"
L["Phased"] = "단계별"
L["Play sound on highlight"] = "강조 시 소리 재생"
L["Player"] = "플레이어"
L["player"] = "플레이어"
L["Player Heals"] = "플레이어 치유"
L["Plays a sound when a removable aura is found on a unit. Does not affect target units."] = "유닛에 제거할 수 있는 오라가 발견되면 소리를 재생합니다. 대상 유닛에 영향을 미치지 않습니다."
L["Poison"] = "독"
L["Portrait"] = "초상화"
L["Portrait Zoom"] = "초상화 줌"
--[[Translation missing --]]
L["Portraits are not clickable or interactable in free floating mode."] = "Portraits are not clickable or interactable in free floating mode."
L["Position"] = "위치"
L["Power"] = "자원"
L["Power Color"] = "자원 색상"
L["Power Colors"] = "자원 색상"
L["Power Height"] = "자원 높이"
L["Power Tag"] = "자원  태그"
L["Power Text"] = "자원 문자"
L["Power Texture"] = "자원 무늬"
L["PowerPerc"] = "자원: %"
L["PvPCombat"] = "PvP"
L["Reaction Colors"] = "반응 색상"
L["Ready"] = "준비완료 상태"
L["Reduce background color's brightness by this percentage."] = "이 비율로 배경 색상의 밝기를 줄입니다."
L["Reduce Bar color's brightness by this percentage."] = "이 비율로 바 색상의 밝기를 줄입니다."
L["Reduce each segment's brightness by this percentage."] = "이 비율로 각 부분의 밝기를 줄입니다."
--[[Translation missing --]]
L["Remaining"] = "Remaining"
L["Remove Text Area"] = "문자 영역 제거"
L["Remove Text Area from this unit with this name."] = "\"이 이름으로 이 유닛에서 문자 영역을 제거합니다."
--[[Translation missing --]]
L["Replace frame with Vehicle"] = "Replace frame with Vehicle"
L["Rest"] = "휴식"
L["Retail"] = "격아"
L["Reverse"] = "반전"
--[[Translation missing --]]
L["Reverse Spiral"] = "Reverse Spiral"
L["Right"] = "오른쪽"
--[[Translation missing --]]
L["Role"] = "Group Role"
L["Rotation"] = "회전"
L["Rows"] = "행"
--[[Translation missing --]]
L["RUF [|c5500DBBDRaeli's Unit Frames|r] needs to reload your UI to properly finish installing on first use. Please do this now."] = "RUF [|c5500DBBDRaeli's Unit Frames|r] needs to reload your UI to properly finish installing on first use. Please do this now."
L["Runes - Blood"] = "룬 - 혈기"
L["Runes - Frost"] = "룬 - 냉기"
L["Runes - Unholy"] = "룬 - 부정"
L["Segment Multiplier"] = "분할 배율"
L["Separate Bar"] = "별도 바"
L["Set class colors to the default Blizzard colors."] = "기본 블리자드 색상으로 직업 색상을 설정합니다."
--[[Translation missing --]]
L["Sets if RUF will use class colours from the Class Colors addon if you have it installed."] = "Sets if RUF will use class colours from the Class Colors addon if you have it installed."
L["Sets this to hidden if your primary resource is mana, so it only shows if you have a class resource, such as Maelstrom."] = "주력 자원이 마나인 경우 이를 숨기고, 소용돌이와 같은 직업 자원이 있는 경우에만 표시하도록 설정합니다."
L["Shadow"] = "그림자"
L["Show %s"] = "%s 표시"
--[[Translation missing --]]
L["Show buffs cast by %s on this unit."] = "Show buffs cast by %s on this unit."
--[[Translation missing --]]
L["Show Classification"] = "Show Classification"
--[[Translation missing --]]
L["Show Classification before Level"] = "Show Classification before Level"
--[[Translation missing --]]
L["Show debuffs cast by %s on this unit."] = "Show debuffs cast by %s on this unit."
L["Show Group Members"] = "그룹원 보기"
L["Show in Raid"] = "공격대 시 보기"
L["Show Level"] = "레벨 보기"
--[[Translation missing --]]
L["Show Max at Max"] = "Show Max at Max"
L["Show only auras you can dispel"] = "당신이 해제할 수 있는 오라만 보기"
L["Show Only Dispellable"] = "해제 가능한 것만 보기"
--[[Translation missing --]]
L["Show Others"] = "Show Others"
L["Show Percentage at Max"] = "최대 백분율 보기"
L["Show Player"] = "플레이어 보기"
L["Show the ++ for rare elites, + for elites etc."] = "희귀정예는 ++, 정예는 +, 등으로 보기"
L["Show Unit in Test Mode"] = "테스트 모드 시 유닛 보기"
L["Show Unlimited Duration"] = "제한없는 지속시간 보기"
--[[Translation missing --]]
L["Shows all unitframes so you can easily configure them."] = "Shows all unitframes so you can easily configure them."
--[[Translation missing --]]
L["Shows the player in the party frames."] = "Shows the player in the party frames."
L["Simple Border"] = "간단한 테두리"
L["Size"] = "크기"
L["Size relative to the aura icon"] = "오라 아이콘을 기준으로 한 크기"
--[[Translation missing --]]
L["Smooth transitions"] = "Smooth transitions"
L["Smoothly animate bar changes. Does not affect class resources that are split into chunks such as Combo Points, or Holy Power."] = "바의 변경을 부드럽게 움직입니다. 연계 점수나 신성한 힘과 같이 덩어리로 분할된 직업 자원에는 영향을 미치지 않습니다."
L["Sort By"] = "정렬 기준"
L["Sort Direction"] = "정렬 방향"
L["Sorting"] = "정렬"
L["Sound"] = "소리"
--[[Translation missing --]]
L["Spell Name"] = "Spell Name"
--[[Translation missing --]]
L["Stagger - High"] = "Stagger - High"
--[[Translation missing --]]
L["Stagger - Low"] = "Stagger - Low"
--[[Translation missing --]]
L["Stagger - Medium"] = "Stagger - Medium"
L["Standard"] = "보통"
--[[Translation missing --]]
L["Starts the cooldown spirals as empty, filling up as the aura runs out."] = "Starts the cooldown spirals as empty, filling up as the aura runs out."
L["Tag"] = "태그"
L["Tags"] = "태그"
L["Tapped"] = "클릭됨"
L["target"] = "대상"
L["Targeting alpha"] = "대상 선택 투명도"
L["TargetMark"] = "대상 징표"
L["targettarget"] = "대상의 대상"
--[[Translation missing --]]
L["targettargettarget"] = "Target's Target's Target"
L["Test Mode"] = "테스트 모드"
--[[Translation missing --]]
L["Text Case"] = "Text Case"
L["Texts"] = "문자"
L["Texture"] = "무늬"
L["The border on buff or debuff icons that is colored using the colors above."] = "버프나 디버프 아이콘의 테두리는 위의 색상을 사용하여 색칠됩니다."
L["The colour options below are listed in order of precedence left to right, with the first being the highest priority."] = "아래의 색상 설정은 우선 순위가 왼쪽에서 오른쪽으로 순서대로 나열되며, 첫 번째가 가장 높은 우선 순위입니다."
--[[Translation missing --]]
L["The damaged alpha will only be used when you are below this percentage of health."] = "The damaged alpha will only be used when you are below this percentage of health."
L["The name of the frame for the unit to anchor to. Defaults to UI Parent if set blank."] = "기준으로 할 유닛에 대한 프레임의 이름입니다. 공란으로 설정하면 부모UI가 기본값입니다."
L["The unit frame border that glows when the unit has a dispellable buff or debuff."] = "유닛에 해제가능한 버프 또는 디버프가 있을 때 유닛 프레임 테두리를 빛나게 합니다."
L["These settings affect all frames."] = "이 설정은 모든 프레임에 적용됩니다."
L["Thick Outline"] = "두꺼운 외곽선"
L["Thickness of the highlight."] = "강조의 두께입니다."
L["This syncs with other addons that support NickTag-1.0 such as Details!"] = "이것은 Details!와 같이 NickTag-1.0을 지원하는 다른 애드온과 동기화됩니다."
--[[Translation missing --]]
L["Time"] = "Time"
L["Time Remaining"] = "남은 시간"
L["Toggle on to force text element to be set to a custom width. If the text is longer than the width, truncation will occur."] = "문자 요소가 사용자정의 너비로 설정되도록 설정합니다. 만약 문자가 너비보다 길면 잘립니다."
--[[Translation missing --]]
L["Toggles the display of Nicknames from players with addons that use NickTag-1.0 such as Details!"] = "Toggles the display of Nicknames from players with addons that use NickTag-1.0 such as Details!"
L["Top"] = "상단"
L["Top-left"] = "왼쪽 상단"
L["Top-right"] = "오른쪽 상단"
--[[Translation missing --]]
L["Transition duration"] = "Transition duration"
--[[Translation missing --]]
L["Trigger below this percent"] = "Trigger below this percent"
--[[Translation missing --]]
L["Trim"] = "Trim"
--[[Translation missing --]]
L[ [=[Trim simply removes any letters above the limit.
Elipsis adds an elipsis to the end of the trimmed name to signify it has been cut short.
Abbreviate turns any words that would be trimmed into an initial.
Initialism turns the entire name into initials if it would be trimmed.]=] ] = [=[Trim simply removes any letters above the limit.
Elipsis adds an elipsis to the end of the trimmed name to signify it has been cut short.
Abbreviate turns any words that would be trimmed into an initial.
Initialism turns the entire name into initials if it would be trimmed.]=]
L["Trivial"] = "하급"
L["Type"] = "유형"
L["Unfriendly"] = "비우호적"
L["Unit Options"] = "유닛 설정"
L["Unitframe Overlay"] = "유닛프레임 오버레이"
L["Up"] = "위"
L["Upper Case"] = "대문자"
--[[Translation missing --]]
L["URL"] = "URL"
--[[Translation missing --]]
L["Use a different alpha value for the player frame when you are under max health."] = "Use a different alpha value for the player frame when you are under max health."
L["Use a different alpha value when you have a target."] = "대상이 있을 때에 다른 투명도 값을 사용합니다."
L["Use Bar Color"] = "바 색상 사용"
L["Use Blizard Colors"] = "블리자드 색상 사용"
L["Use Class Colors addon"] = "직업 색상 애드온 사용"
--[[Translation missing --]]
L["Vertical"] = "Vertical"
L["Vertical Growth"] = "수직 성장"
L["Vertical Offset from the Anchor."] = "기준으로부터의 수직 좌표입니다."
L["Vertical Offset from the Frame Anchor."] = "프레임 기준으로부터의 수직 좌표입니다."
L["Vertical Offset from the previous unit in the group."] = "그룹 안 이전 유닛으로부터의 수직 좌표입니다."
L["Vertical Spacing"] = "수직 간격"
--[[Translation missing --]]
L["Vertical stacking or horizontal stacking."] = "Vertical stacking or horizontal stacking."
L["Very Hard"] = "매우 어려움"
--[[Translation missing --]]
L["When reporting an issue, please also post the revision number above. Thanks!"] = "When reporting an issue, please also post the revision number above. Thanks!"
L["Width"] = "너비"
L["X Offset"] = "X 좌표"
L["X Spacing"] = "X 간격"
L["Y Offset"] = "Y 좌표"
L["Y Spacing"] = "Y 간격"
L["You have the %s version of RUF installed, but you are playing %s. Please install a compatible version."] = "당신은 RUF %s 버전이 설치되어 있습니다. 그러나 당신은 %s에서 사용중 입니다. 호환되는 버전을 설치하시길 바랍니다."
L["Z Offset"] = "Z 좌표"